services:
  - type: web
    name: agricure-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.server:app
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: WEATHER_API_KEY
        sync: false
    plan: starter
